name: 定时运行 Python 脚本

on:
  schedule:
    # 每天 北京时间 09:30
    - cron: '30 1 * * *'
    # 每天 北京时间 11:30
    - cron: '30 3 * * *'
    # 每天 北京时间 13:30
    - cron: '30 5 * * *'
    # 每天 北京时间 14:45
    - cron: '45 6 * * *'
    # 每天 北京时间 16:00
    - cron: '0 8 * * *'
    # 每天 北京时间 20:00
    - cron: '0 12 * * *'
    
  # 允许手动点击运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 运行脚本
        run: python hstech-model.py
